/**
 * OffersContext + useOffers hook.
 *
 * Maintains exactly 3 unique offers at any time. On win, the played offer
 * is removed, the remaining two are shuffled, and a new unique offer is
 * appended — so the user always sees 3 different games.
 */
import { createContext, useCallback, useContext, useEffect, useState } from "react";
import { streamOffers, pickReplacementOfferAsync, pickReplacementOffer } from "../services/offerStream";
import type { Offer, GameType } from "../types/offer";

interface OffersContextValue {
  offers: Offer[];
  isStreaming: boolean;
  removeAndReplace: (offerId: string) => void;
}

export const OffersContext = createContext<OffersContextValue | null>(null);

export function useOffers(): OffersContextValue {
  const ctx = useContext(OffersContext);
  if (!ctx) throw new Error("useOffers must be used within OffersProvider");
  return ctx;
}

export function useOffersProvider(walletConnected: boolean): OffersContextValue {
  const [offers, setOffers] = useState<Offer[]>([]);
  const [isStreaming, setIsStreaming] = useState(false);

  // Stream initial 3 when wallet connects
  useEffect(() => {
    if (!walletConnected) {
      setOffers([]);
      return;
    }

    let cancelled = false;
    setIsStreaming(true);
    setOffers([]);

    streamOffers(
      (offer) => {
        if (!cancelled) setOffers((prev) => [...prev, offer]);
      },
      () => {
        if (!cancelled) setIsStreaming(false);
      },
    );

    return () => { cancelled = true; };
  }, [walletConnected]);

  /**
   * Remove the given offer, shuffle the remaining two, append a new offer
   * whose game type differs from the two visible ones. Guarantees the
   * 3 displayed offers always have 3 different game types.
   *
   * The replacement offer is generated by the AI when possible; on any
   * failure we fall back to the static pool so the UI never stalls.
   */
  const removeAndReplace = useCallback((offerId: string) => {
    // 1. Synchronously remove the played offer and shuffle the other two.
    //    A static-pool placeholder is appended so the list is always 3 long.
    let snapshotGameTypes: GameType[] = [];
    let snapshotTitles: string[] = [];
    setOffers((prev) => {
      const remaining = prev.filter((o) => o.id !== offerId);
      if (remaining.length >= 2 && Math.random() < 0.5) {
        [remaining[0], remaining[1]] = [remaining[1], remaining[0]];
      }
      const visibleGameTypes = remaining.map((o) => o.gameType);
      const visibleTitles = remaining.map((o) => o.title);
      snapshotGameTypes = visibleGameTypes;
      snapshotTitles = visibleTitles;
      const fallback = pickReplacementOffer(visibleGameTypes, visibleTitles);
      return fallback ? [...remaining, fallback] : remaining;
    });

    // 2. In the background, ask the AI for a better replacement; swap it in
    //    only if the gameType still matches (i.e. user hasn't played again).
    (async () => {
      try {
        const aiOffer = await pickReplacementOfferAsync(snapshotGameTypes, snapshotTitles);
        if (!aiOffer) return;
        setOffers((prev) => {
          // Replace the tail offer only if its gameType still matches the
          // one we asked the AI for (avoids clobbering a newer state).
          if (prev.length === 0) return prev;
          const last = prev[prev.length - 1];
          if (last.gameType !== aiOffer.gameType) return prev;
          if (last.id === aiOffer.id) return prev; // already applied
          // Avoid duplicate titles across the visible set
          if (prev.slice(0, -1).some((o) => o.title === aiOffer.title)) return prev;
          return [...prev.slice(0, -1), aiOffer];
        });
      } catch {
        // swallow — fallback offer is already in place
      }
    })();
  }, []);

  return { offers, isStreaming, removeAndReplace };
}